// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Category         string
	Expenses         string
	SchemaMigrations string
	Users            string
}{
	Category:         "category",
	Expenses:         "expenses",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
